# Replace with your actual OpenAI API Key
OPENAI_API_KEY = "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"
