# Replace with your actual OpenAI API Key
OPENAI_API_KEY = "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"
